### PR TITLE
Add support for dummy interfaces and route command

### PR DESCRIPTION
**Pull request by deitch**
Pretty straightforward. Allows to create a dummy interface inside a container.

### CODE REVIEW

**Comment by deitch** [comment]
Any comment? I have another issue with DHCP, happy to fix and open a PR once this one is in...

**Comment by deitch** [comment]
Also adds support for generated mac address with uniqueness.

If the mac address follows the pattern with `U:<string>`, then it will use `<string>` to generate a unique mac address in the Locally Administered range. This allows people to have unique and repeatable mac addresses, without needing to manually manage and enter them.

Most common use case, of course, is to use hostname.

**Comment by jpetazzo** [comment]
Hi!

Sorry for the delay; I have only very little time to maintain pipework so sometimes the PRs stay around for a while.

If I understand correctly, there are 3 features here. 

---

#### Support for dummy interface

This is simple and straightforward. What is the use-case though? (I'm curious :-))

#### `pipework route`

That's smart. I wonder, however, if it could be a separate tool (or at least, if the code could be cleanly separated to avoid cluttering pipework itself). The only common code would be the container/PID resolution code, right?

#### MAC address generation

Nice too! And clever. I like :-) Could you add a doc paragraph in the README, though?

---

Do you think you could submit 3 separate PR? That would be really cool. That way, I can merge whatever is merge-able without delaying it if we discuss the other features.

Thank you so much!

**Comment by deitch** [comment]
Hi @jpetazzo 

Sure, I will split it up into 3 PRs. I kind of just did them one by one without paying attention and github merged them all into one. Once I do, though, we can close this one.

### support for dummy interface

> what's the use case?

There are times when you need an actual additional interface on a host or in a container. Sometimes apps do weird things like requiring a real interface to function, even if disconnected. Samba sometimes has strange behaviour in that respect, and I know of one financial app I am dealing with that requires it.

### route

> The only common code would be the container/PID resolution code, right?

Yes. And to be honest, there are a few extra `if`/`then` statements because this is the only one that doesn't create an additional interface for the container. That having been said, the container/PID resolution code is pretty darn good, and the real beauty of pipework. I wouldn't want to have another tool. :-)

### MAC address generation

> Could you add a doc paragraph in the README, though?

Sure thing. I just used my own modified version at a client's deployment. It solved significant DHCP headaches. 

Of course, don't try it on a VM in vmware which insists on macs in their private address range....

I will get to this over the week,

**Comment by jpetazzo** [comment]
Sweet! OK then, I'd suggest to make PRs for dummy interfaces and MAC address generation.

For `ip route` ... GIve me a couple of days (it's an extended week-end here and I've decided to spend some time on pipework), we'll see what I can come up with :-)

**Comment by deitch** [comment]
That is how you are spending Labor Day?? Well, better than me on an airplane, I guess.

**Comment by deitch** [comment]
Dang, how do I get it into 3 separate PRs? PR seems to take all of the commits. Do I need separate branches for each PR? Is there any way to do a PR from a particular commit in a branch, not just the most recent?

**Comment by deitch** [comment]
OK, all three done as topic branches. I will create the PRs later today and then close this one.

**Comment by deitch** [comment]
OK, 3 PRs all in. I am closing this one in favour of those three.

**Comment by jpetazzo** [comment]
Cool, thanks! Looks like the PRs need to be rebased though :-/ 

Let me know if you'll need help with that.

**Pull request closed without merging**
