### PR TITLE
Microoptimization

### PR DESCRIPTION
**Pull request by kojiromike**
Replace a few subshells with case pattern matching and POSIX parameter expansion.

(Done TTW, but happy to sign off or tweak if need be.)

### CODE REVIEW

**Comment by jpetazzo** [comment]
Oh that's... Nice! Do you think you could break it over multiple lines, just for readability?

(I know, I'm nitpicking, but we're not getting bonus for sticking within a low line count, so ... :-D)

Thanks a lot!

**Comment by kojiromike** [comment]
OK. How's this? Since it's necessary to do the VLAN in two assignments, but with one end result, I kept that part on one line.

**Comment by kojiromike** [comment]
I also updated it to include one other place where this same pattern happens.

**Comment by jpetazzo** [comment]
Thanks!

**Pull request merged**
