### PR TITLE
Add support for routes

### PR DESCRIPTION
**Pull request by deitch**
Add support for route. Anything after "pipework <CONTAINER_ID> route" will be passed to `ip route` run inside the container.

### CODE REVIEW

**Comment by deitch** [comment]
And rebase done here too.

**Comment by shisoft** [comment]
+1 When static ip erases the container routes

**Comment by deitch** [comment]
Hey @jpetazzo, this has been open for 3 months. May I request a bump?

**Comment by deitch** [comment]
Bump?

**Comment by jpetazzo** [comment]
Damn, that one was pretty useful but it was buried under other notifications :-(

If you're still interested let me know and we can coordinate to get it merged.

**Comment by deitch** [comment]
> Damn, that one was pretty useful 

Thanks!

> If you're still interested let me know and we can coordinate to get it merged.

Sure. Let's go for it. I guess I will need to rebase it, but it shouldn't be too hard. I just want to do it when you are ready, so I can rebase and get it in immediately.

**Comment by jpetazzo** [comment]
Now is a good time. I'll monitor notifications closely this week and next week before heading to CRAFT in Budapest! :)

**Comment by deitch** [comment]
Wow, craft-conf.com looks amazing!

**Comment by deitch** [comment]
Have I mentioned how much I hate rebasing after many changes? So much manual work...

**Comment by deitch** [comment]
Yes! Done! OK, @jpetazzo , in your hands.

**Comment by jpetazzo** [comment]
And it's merged! Thanks a lot for the contribution, and sorry for the frustrating rebases.

**Comment by deitch** [comment]
Glad it helps. Funny, how your early notes had that someday this will be deprecated in favour of docker features. It still exists and is quite useful!

**Comment by apakhomov** [comment]
Please, take a look on my comment to that commit... https://github.com/jpetazzo/pipework/commit/f062bc933e3326ce5902fb2b26436c13ab4de17d

**Comment by jpetazzo** [comment]
I'll push a quick fix shortly

On Fri, Apr 15, 2016 at 5:39 AM, Anton Pakhomov <notifications@github.com>
wrote:

> Please, take a look on my comment to that commit... f062bc9
> <https://github.com/jpetazzo/pipework/commit/f062bc933e3326ce5902fb2b26436c13ab4de17d>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jpetazzo/pipework/pull/174#issuecomment-210448423>
>



-- 
@jpetazzo <https://twitter.com/jpetazzo>
http://jpetazzo.github.io/
<http://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/>

**Comment by deitch** [comment]
> On Ubuntu 14.04 with typical /bin/sh linked to dash gives error

Well, crap. I forgot about that. `dash` doesn't support that string substitution syntax? 

> Also "case" between lines 113-114 is missing ";;"

Good catch

> Line 271: strange syntax. ] and [ are missing: [ "$IFTYPE" != "route" ] && [ "$IFTYPE" != "dummy" ]

Yeah, I got so used to doing bash that when I rebased and merged....

Both of these are due to that.

@jpetazzo do you want me to patch and submit a new PR? Or can you quickly patch it?

**Comment by deitch** [comment]
Thanks for the quick patch @jpetazzo

**Pull request merged**
