### PR TITLE
Add support for dummy interface

### PR DESCRIPTION
**Pull request by deitch**
Allows to create a dummy interface inside a container.

### CODE REVIEW

**Comment by jpetazzo** [comment]
Thanks! Can you rebase it though? Sorry, I think it must have conflicted with the other changes I merged recently...

**Comment by deitch** [comment]
Oh crap. I see the notification now, I missed that earlier. 

How do I do this? My branches are based on my master which is a fork of your master. 

Is there an easy way in github to just update my fork master to your master, and then I can pull to my laptop and rebase my branches? Or do I need to pull your latest master onto my master on my laptop, push to my master and then I can rebase my branches?

**Comment by deitch** [comment]
OK, never mind. I found the github help page, they say to do just that: add your repo as `upstream`, fetch it, merge into my master and push. Done. Now I need to figure out why rebase doesn't work.

**Comment by deitch** [comment]
Got it! OK, doing for the others as well.

**Comment by jpetazzo** [comment]
I rebased and merge it myself. Thank you for contributing this!

**Comment by deitch** [comment]
My pleasure. Thanks for the great project.

**Pull request merged**
